name: ebidence
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.20.1
  screen_recorder: ^0.3.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  flash_card: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/movies/

  fonts:
    - family: NotoSansJP
      fonts: 
        - asset: assets/fonts/NotoSansJP-Bold.ttf
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
 
  uses-material-design: true
